server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/VirtualMuseum?serverTimezone=Europe/Belgrade
    username: root
    password: amazing284,

  mail:
    host: smtp.gmail.com
    port: 587
    username: njegos.dukic.998@gmail.com
    password: cqchqorzmwpddtwy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    open-in-view: false

    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

jwt:
  secret: 12345678
  duration: 1d