server:
  port: 9000


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/VirtualMuseum?serverTimezone=Europe/Belgrade
    username: root
    password: amazing284,

  jpa:
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    open-in-view: false

jwt:
  secret: 12345678
  duration: 1d