/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.56
 * Generated at: 2022-01-11 19:32:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.unibl.etf.virtualmuseum.entities.UserEntity;
import org.unibl.etf.virtualmuseum.services.UserService;

public final class EditUser_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.unibl.etf.virtualmuseum.entities.UserEntity");
    _jspx_imports_classes.add("org.unibl.etf.virtualmuseum.services.UserService");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      org.unibl.etf.virtualmuseum.beans.UserBean user = null;
      synchronized (session) {
        user = (org.unibl.etf.virtualmuseum.beans.UserBean) _jspx_page_context.getAttribute("user", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (user == null){
          user = new org.unibl.etf.virtualmuseum.beans.UserBean();
          _jspx_page_context.setAttribute("user", user, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("  \r\n");
      out.write(" \r\n");

	UserEntity ue = null;

	if (!user.isLoggedIn()) {
		response.sendRedirect("Login.jsp");
	}
	
	else if (request.getParameter("logout") != null) {
		user.logOut();
		session.invalidate();
		response.sendRedirect("Login.jsp");
	}
	
	else {
		String id = request.getParameter("current-id");
	    String username = request.getParameter("current-username");
		String firstName = request.getParameter("current-firstName");
		String lastName = request.getParameter("current-lastName");
		String email = request.getParameter("current-email");
	    if(id != null && username != null && firstName != null && lastName != null && email != null) {
	    	ue = new UserEntity(Integer.parseInt(id), username, firstName, lastName, email);
	    }
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("	<head>\r\n");
      out.write("    	<meta charset=\"UTF-8\">\r\n");
      out.write("    	<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    	<title>Virtual Museum Admin</title>\r\n");
      out.write("    	<link href=\"../css/Header.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    	<link href=\"../css/AddEdit.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    	<link rel=\"icon\" href=\"../images/logo.png\">\r\n");
      out.write("    	<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    	<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    	<link href=\"https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap\" rel=\"stylesheet\"> 				\r\n");
      out.write("	</head>\r\n");
      out.write("	\r\n");
      out.write("	<body>\r\n");
      out.write("		<div class=\"header-container\">\r\n");
      out.write("            <div class=\"header-logo-container\">\r\n");
      out.write("				<a class=\"header-logo-container\" href=\"Homepage.jsp\">\r\n");
      out.write("			    	<img class=\"header-logo\" src=\"../images/logo.png\" />\r\n");
      out.write("			    </a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"header-title\">\r\n");
      out.write("                VIRTUAL MUSEUM ADMINISTRATION\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"header-login-container\">\r\n");
      out.write("				<form class=\"header-login-container\" action=\"#\" method=\"post\">\r\n");
      out.write("	                <div class=\"header-login-label\">\r\n");
      out.write("	                    ");
      out.print( user.getUsername() );
      out.write(" \r\n");
      out.write("	                </div>\r\n");
      out.write("	                <input type=\"hidden\" name=\"logout\" value=\"1\" />\r\n");
      out.write("		            <input type=\"image\" class=\"header-login-image\" src=\"../images/login.png\" />\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"museum-edit-container\">\r\n");
      out.write("	        <form action=\"Users.jsp\" method=\"post\" class=\"museum-edit-form\">\r\n");
      out.write("	        	<input name=\"id\" type=\"hidden\" value=");
      out.print( (ue == null ? "" : ue.getId()) );
      out.write(">\r\n");
      out.write("	            <div class=\"museum-edit-single-input\">\r\n");
      out.write("	                <label class=\"museum-edit-input-label\" for=\"username\">Username: </label>\r\n");
      out.write("	                <input class=\"museum-edit-input-field\" name=\"username\" type=\"text\" value=\"");
      out.print( (ue == null ? "" : ue.getUsername()) );
      out.write("\" required>\r\n");
      out.write("	            </div>\r\n");
      out.write("	            <div class=\"museum-edit-single-input\">\r\n");
      out.write("	                <label class=\"museum-edit-input-label\" for=\"firstName\">First name: </label>\r\n");
      out.write("	                <input class=\"museum-edit-input-field\" name=\"firstName\" type=\"text\" value=\"");
      out.print( (ue == null ? "" : ue.getFirstName()) );
      out.write("\" required>\r\n");
      out.write("	            </div>\r\n");
      out.write("	            <div class=\"museum-edit-single-input\">\r\n");
      out.write("	                <label class=\"museum-edit-input-label\" for=\"lastName\">Last name: </label>\r\n");
      out.write("	                <input class=\"museum-edit-input-field\" name=\"lastName\" type=\"text\" value=\"");
      out.print( (ue == null ? "" : ue.getLastName()) );
      out.write("\" required>\r\n");
      out.write("	            </div>\r\n");
      out.write("	            <div class=\"museum-edit-single-input\">\r\n");
      out.write("	                <label class=\"museum-edit-input-label\" for=\"email\">Email: </label>\r\n");
      out.write("	                <input class=\"museum-edit-input-field\" name=\"email\" type=\"email\" value=\"");
      out.print( (ue == null ? "" : ue.getEmail()) );
      out.write("\" required>\r\n");
      out.write("	            </div>\r\n");
      out.write("	            <div class=\"museum-edit-single-input margin-botton-4perc\">\r\n");
      out.write("	                <input class=\"museum-edit-input-field\" type=\"submit\" value=\"Update User\">\r\n");
      out.write("	            </div>\r\n");
      out.write("	        </form>\r\n");
      out.write("	    </div>\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
